# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/lib/python3.10/site-packages/cmake/data/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/lib/python3.10/site-packages/cmake/data/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/speedypleath/b2bAI/midi_generator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/speedypleath/b2bAI/midi_generator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/lib/python3.10/site-packages/cmake/data/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/lib/python3.10/site-packages/cmake/data/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/speedypleath/b2bAI/midi_generator/CMakeFiles /Users/speedypleath/b2bAI/midi_generator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/speedypleath/b2bAI/midi_generator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named note

# Build rule for target.
note: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 note
.PHONY : note

# fast build rule for target.
note/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/note.dir/build.make CMakeFiles/note.dir/build
.PHONY : note/fast

#=============================================================================
# Target rules for targets named pymodule

# Build rule for target.
pymodule: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pymodule
.PHONY : pymodule

# fast build rule for target.
pymodule/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pymodule.dir/build.make CMakeFiles/pymodule.dir/build
.PHONY : pymodule/fast

lib/API.o: lib/API.cpp.o
.PHONY : lib/API.o

# target to build an object file
lib/API.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/note.dir/build.make CMakeFiles/note.dir/lib/API.cpp.o
.PHONY : lib/API.cpp.o

lib/API.i: lib/API.cpp.i
.PHONY : lib/API.i

# target to preprocess a source file
lib/API.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/note.dir/build.make CMakeFiles/note.dir/lib/API.cpp.i
.PHONY : lib/API.cpp.i

lib/API.s: lib/API.cpp.s
.PHONY : lib/API.s

# target to generate assembly for a file
lib/API.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/note.dir/build.make CMakeFiles/note.dir/lib/API.cpp.s
.PHONY : lib/API.cpp.s

lib/pybind.o: lib/pybind.cpp.o
.PHONY : lib/pybind.o

# target to build an object file
lib/pybind.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pymodule.dir/build.make CMakeFiles/pymodule.dir/lib/pybind.cpp.o
.PHONY : lib/pybind.cpp.o

lib/pybind.i: lib/pybind.cpp.i
.PHONY : lib/pybind.i

# target to preprocess a source file
lib/pybind.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pymodule.dir/build.make CMakeFiles/pymodule.dir/lib/pybind.cpp.i
.PHONY : lib/pybind.cpp.i

lib/pybind.s: lib/pybind.cpp.s
.PHONY : lib/pybind.s

# target to generate assembly for a file
lib/pybind.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pymodule.dir/build.make CMakeFiles/pymodule.dir/lib/pybind.cpp.s
.PHONY : lib/pybind.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... note"
	@echo "... pymodule"
	@echo "... lib/API.o"
	@echo "... lib/API.i"
	@echo "... lib/API.s"
	@echo "... lib/pybind.o"
	@echo "... lib/pybind.i"
	@echo "... lib/pybind.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

